### ISSUE TITLE
Special folders request

### ISSUE THREAD

**Issue by AlexGamerTrue** [dalps/minecraft11#1]
Hey dude! I loved the folder designs you made and wanted to request a folder design for the other folder too, i think the ME 
Crafting Terminal from Applied Energistics 2 would look really cool for the downloads folder
![imagem_2023-11-24_135313430](https://github.com/dalps/minecraft11/assets/87259136/c4a113e2-90de-4cea-8233-fc7df089c16e)
For the Images folder i think that the Knowledge book would be fit
![image](https://github.com/dalps/minecraft11/assets/87259136/2ef33758-f2c8-4b9b-9b54-3c656d3852c9)
For the Documents, the bookshelf
For the Music one, Noteblock!
For videos, the observer
That's all for now

**Comment by dalps** [comment]
Thanks for the really cool requests @AlexGamerTrue, very excited to work on them! :)
What do you think of the bookshelf and noteblock folders I added yesterday?

**Comment by AlexGamerTrue** [comment]
I'll be honest, i think they would look better if they looked more like the original block, since if you look at them you cant really know it's even from minecraft.
![imagem_2023-11-26_214747025](https://github.com/dalps/minecraft11/assets/87259136/26947ce4-cef1-4df3-a3b6-faf2f8f678ba)
See what i mean? There you can see they are the blocks they are, but in folder format. That was what i was expecting. What you did is well made, but i was hoping for them to be more like the blocks themselves. If you get what i mean. Continue the amazing work and good luck!

**Comment by dalps** [comment]
I see what you mean. My intention for them was to recreate the folder shape in pixel art but there's just not enough detail and the result is weird yeah (also inconsistent with the other designs).
I fixed the noteblock icon, but fitting the bookshelf texture is the challenge here. I can't just slap on the original texture as it looks bad imo:
![bookshelf-v3](https://github.com/dalps/minecraft11/assets/96267363/c0387571-851e-4bfd-94c2-9e28e0f30190)
So I came up with two other versions (both required some light editing of the original texture):
a) 
![bookshelf-v4](https://github.com/dalps/minecraft11/assets/96267363/a9484728-c442-4ca9-8b26-065007fdec96)
b) 
![bookshelf-v6](https://github.com/dalps/minecraft11/assets/96267363/03119ec4-3b00-4d9c-9490-e5c2813e2a85)
Do tell me which one should be the new bookshelf icon, or feel free to suggest more improvements! Thanks for the honest critique!

**Comment by AlexGamerTrue** [comment]
a) looks better! looks more colorful. That's exactly what my objective was, it looks amazing!

**Comment by AlexGamerTrue** [comment]
Hi?

**Comment by dalps** [comment]
Hey! Sorry for leaving this issue open, life got in the way.
I'm hesitant of making your remaining two requests because I don't think they would be a good fit for the collection: the downloads icon you suggested isn't vanilla minecraft, and the knowledge book is neither a mob or a block (what this icon collection is about). For these reasons I won't make them, however I can upload a blank icon template for you (and anyone willing) to edit and create your own icons! Tell me what you think, then I'll close this issue.

**Comment by AlexGamerTrue** [comment]
Sure! Sounds amazing

**Comment by dalps** [comment]
There you go! Might continue this project in the future...
If you have more questions or ideas, feel free to open another issue~ closing this one
