### ISSUE TITLE
[Question] Version Differences

### ISSUE THREAD

**Issue by CorruptionVR** [dalps/minecraft11#2]
hey, I have a question. why do some of the SVG files look incomplete? an example of this is the creeper.svg file, where the entire front is missing.

**Comment by dalps** [comment]
It depends on where you're previewing the SVG. Browsers don't handle the Inkscape tags inside the SVG very well, so they render it in a weird way. Here's what I see if I click on the .svg on Chrome:

![image](https://github.com/dalps/minecraft11/assets/96267363/7fcaa21c-47e4-425a-bc00-cb3ea32a1519)

But in Inkscape it works just fine, all textures are embedded in the SVG file and you should see them too.

On that note, I should probably normalize the SVGs to make them browser-friendly.
